site_name: Pipeline de Dados - SQL Server, MinIO e Delta
site_description: Documentação do Trabalho 2 de Engenharia de Dados
theme:
  name: readthedocs

nav:
  - Contextualização e Cenário: index.md
  - Apache Spark e PySpark: spark.md
  - Delta Lake: delta.md
  - Implementação Prática (CRUD): implementacao.md
