site_name: Pipeline de Dados - SQL Server, MinIO e Delta
site_description: Documentação do Trabalho 2 de Engenharia de Dados
theme:
  name: readthedocs

nav:
  - Contextualização Inicial: index.md
  - 1. Extração para Landing Zone: req1_extracao.md
  - 2. Conversão para Delta (Bronze): req2_bronze.md
  - 3. Operações DML no Delta: req3_dml.md
